security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_OWNER, ROLE_MASTER, ROLE_OPERATOR, ROLE_ALLOWED_TO_SWITCH]
        ROLE_OWNER: [ROLE_OWNER, ROLE_MASTER, ROLE_OPERATOR]
        ROLE_MASTER: [ROLE_MASTER]
        ROLE_OPERATOR: [ROLE_OPERATOR, ROLE_VIEW, ROLE_CREATE, ROLE_EDIT, ROLE_DELETE]
        ROLE_VIEW: ROLE_VIEW
        ROLE_CREATE: ROLE_CREATE
        ROLE_EDIT: ROLE_EDIT
        ROLE_DELETE: ROLE_DELETE

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout

    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/order, roles: IS_AUTHENTICATED_FULLY }
